# Generated by Django 4.1.7 on 2024-06-22 18:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Booked'), (2, 'Cancelled')])),
                ('bookingDate', models.DateTimeField(default=datetime.datetime(2024, 6, 23, 0, 9, 35, 906062))),
                ('startTime', models.DateTimeField(default=datetime.datetime(2024, 6, 23, 0, 9, 35, 906062))),
                ('endTime', models.DateTimeField(default=datetime.datetime(2024, 6, 23, 0, 9, 35, 906062))),
                ('bookedByUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.TextField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='studio_photos')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studio')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSessionUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Joined'), (2, 'Left'), (3, 'Removed')])),
                ('bookingSession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.bookingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.studio'),
        ),
    ]
