# Generated by Django 5.1 on 2024-08-31 19:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookingsession_studio_profile_location_studiomedia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='bookingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 0, 59, 45, 934878)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 0, 59, 45, 934878)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 0, 59, 45, 934878)),
        ),
        migrations.CreateModel(
            name='BookingSessionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageDatetime', models.DateTimeField(default=datetime.datetime(2024, 9, 1, 0, 59, 45, 935862))),
                ('message', models.TextField(max_length=100000)),
                ('bookingSession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.bookingsession')),
                ('sentByUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingSessionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Pending'), (3, 'Unpaid')])),
                ('paymentDateTime', models.DateTimeField(default=datetime.datetime(2024, 9, 1, 0, 59, 45, 935862))),
                ('bookingSession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.bookingsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.IntegerField(choices=[(1, 'Studio Owner'), (2, 'User')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
