# Generated by Django 5.1 on 2024-08-31 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bookingsession_bookingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='bookingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 4, 44, 316878)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 4, 44, 316878)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 4, 44, 316878)),
        ),
        migrations.AlterField(
            model_name='bookingsessionchat',
            name='messageDatetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 4, 44, 317877)),
        ),
        migrations.AlterField(
            model_name='bookingsessionpayment',
            name='paymentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 4, 44, 316878)),
        ),
    ]
