# Generated by Django 5.1 on 2024-08-31 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_owner_studio_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='bookingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 19, 58, 631260)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 19, 58, 631260)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 19, 58, 631260)),
        ),
        migrations.AlterField(
            model_name='bookingsessionchat',
            name='messageDatetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 19, 58, 632289)),
        ),
        migrations.AlterField(
            model_name='bookingsessionpayment',
            name='paymentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 1, 19, 58, 631260)),
        ),
    ]
