# Generated by Django 5.1 on 2024-09-01 07:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='email',
            field=models.EmailField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='iconUrl',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='phone_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='bookingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 51, 15, 995778)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 51, 15, 995778)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 51, 15, 995778)),
        ),
        migrations.AlterField(
            model_name='bookingsessionchat',
            name='messageDatetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 51, 15, 996805)),
        ),
        migrations.AlterField(
            model_name='bookingsessionpayment',
            name='paymentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 51, 15, 996805)),
        ),
    ]
