# Generated by Django 5.1 on 2024-09-01 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_studio_email_studio_iconurl_studio_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePhoto',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePicUrl',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='bookingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 13, 40, 2, 969129)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 13, 40, 2, 969129)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 13, 40, 2, 969129)),
        ),
        migrations.AlterField(
            model_name='bookingsessionchat',
            name='messageDatetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 13, 40, 2, 970129)),
        ),
        migrations.AlterField(
            model_name='bookingsessionpayment',
            name='paymentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 13, 40, 2, 970129)),
        ),
    ]
