# Generated by Django 5.1 on 2024-09-01 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_profile_profilephoto_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='verificationStatus',
            field=models.IntegerField(choices=[(1, 'Pending Verification'), (2, 'Verified'), (3, 'Verification Revoked')], default=1),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='bookingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 14, 45, 3, 164759)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 14, 45, 3, 164759)),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 14, 45, 3, 164759)),
        ),
        migrations.AlterField(
            model_name='bookingsessionchat',
            name='messageDatetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 14, 45, 3, 165776)),
        ),
        migrations.AlterField(
            model_name='bookingsessionpayment',
            name='paymentDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 14, 45, 3, 165776)),
        ),
    ]
